hungry=input("are you hungry")
if hungry=="yes":
	print("eat samosa")
	print("eat burger")
	print("krishn")
	print("radha")
	print("krishn")
	print("radha")
	print("krishn")
	print("master")
	print("radha")
	print("krishn")
	print ("master")
	print("radha")
	print("radha radha radha ")
	print("eat pizza")
	print("hare krishn")
	print ("radha krishn radha krishn")
	print("radha krishn")
	print ("radha krishn radha krishn")
	print ("radha krishn radha krishn")
	print("radha krishn")
	print ("radha krishn radha krishn")
	print("adding change in master")
	print("git sita")
else:
	print("you should do your homework")
	print("thirsty branch")
	print("radha radha radha ")
	print("radha radha radha ")
	print("do your homework")
	print("ram")
else:
    print("bhaj hare krishn")
	print("ram")
	print("krishn")
	print("radha")
