hungry=input("are you hungry")
if hungry=="yes":
	print("eat samosa")
	print("eat burger")
	print("eat pizza")
	print ("radha krishn radha krishn")
	print("radha krishn")
	print ("radha krishn radha krishn")
	print("adding change in master")
	print("git sita")
else:
	print("you should do your homework")
	print("thirsty branch")
	print("do your homework")
	print("krishn")
	print("radha")
